"""Alert persistence model — stores every alert generated by the alert engine.

Used for future ML dataset collection and audit trail.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import Float, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from moex_analyst.infrastructure.db.base import Base, TimestampMixin

__all__ = ["AlertRecord"]


class AlertRecord(Base, TimestampMixin):
    __tablename__ = "alert_records"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    ticker: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    timeframe: Mapped[str] = mapped_column(String(4), nullable=False)

    alert_type: Mapped[str] = mapped_column(String(32), nullable=False)
    direction: Mapped[str] = mapped_column(String(16), nullable=False)
    severity: Mapped[str] = mapped_column(String(16), nullable=False)
    score: Mapped[float] = mapped_column(Float, nullable=False)

    message_hash: Mapped[str] = mapped_column(String(64), nullable=False)

    as_of: Mapped[datetime] = mapped_column(nullable=False)
